# P9 - Lapage : Préparation et Analyse des données

---

### Objectifs de cette session

1. **Charger** les 3 fichiers de données (customers, products, transactions)
2. **Inspecter** les données avec une fonction réutilisable
3. **Joindre** les tables pour créer un dataset unifié
---

## 1. Configuration de l'environnement

In [2]:
# Import des bibliothèques
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import date

# Configuration de l'affichage
pd.set_option('display.max_columns', None)  # Afficher toutes les colonnes
pd.set_option('display.max_rows', 100)      # Limiter à 100 lignes
pd.set_option('display.width', None)        # Pas de limite de largeur

# Style des graphiques
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 12

print("✅ Bibliothèques chargées avec succès !")

✅ Bibliothèques chargées avec succès !

---

## 2. Chargement des données

Nous avons 3 fichiers CSV à charger :
- `customers.csv` : informations sur les clients
- `products.csv` : catalogue des produits
- `transactions.csv` : historique des ventes

In [3]:
# Définir le chemin vers les données
# À adapter selon votre structure de projet
DATA_PATH = "../data/"

# Chargement des 3 fichiers
customers = pd.read_csv(DATA_PATH + "raw/customers.csv", sep=";")
products = pd.read_csv(DATA_PATH + "raw/products.csv", sep=";")
transactions = pd.read_csv(DATA_PATH + "raw/transactions.csv", sep=";")

print("✅ Fichiers chargés avec succès !")
print(f"   - customers    : {len(customers):,} lignes")
print(f"   - products     : {len(products):,} lignes")
print(f"   - transactions : {len(transactions):,} lignes")

✅ Fichiers chargés avec succès !
   - customers    : 8,621 lignes
   - products     : 3,286 lignes
   - transactions : 1,048,575 lignes

C:\Users\RémiJulien\AppData\Local\Temp\ipykernel_7420\895322985.py:8: DtypeWarning: Columns (0,1,2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  transactions = pd.read_csv(DATA_PATH + "raw/transactions.csv", sep=";")

### 👀 Premier aperçu rapide

In [21]:
# Aperçu des premières lignes de chaque fichier
print("=" * 60)
print("CUSTOMERS - Premières lignes")
print("=" * 60)
display(customers.head(3))

============================================================
CUSTOMERS - Premières lignes
============================================================

  client_id sex  birth
0    c_4410   f   1967
1    c_7839   f   1975
2    c_1699   f   1984

In [22]:
print("=" * 60)
print("PRODUCTS - Premières lignes")
print("=" * 60)
display(products.head(3))

============================================================
PRODUCTS - Premières lignes
============================================================

  id_prod  price  categ
0  0_1421  19.99      0
1  0_1368   5.13      0
2   0_731  17.99      0

In [23]:
print("=" * 60)
print("TRANSACTIONS - Premières lignes")
print("=" * 60)
display(transactions.head(3))

============================================================
TRANSACTIONS - Premières lignes
============================================================

  id_prod                        date session_id client_id
0  0_1259  2021-03-01 00:01:07.843138        s_1     c_329
1  0_1390  2021-03-01 00:02:26.047414        s_2     c_664
2  0_1352  2021-03-01 00:02:38.311413        s_3     c_580

---

## 3. Fonction d'inspection des données

Plutôt que de répéter les mêmes commandes pour chaque DataFrame, nous allons créer une **fonction réutilisable** qui génère un rapport complet.

### 🎯 Ce que notre fonction doit faire :
1. Afficher les informations générales (`.info()`)
2. Afficher les statistiques descriptives (`.describe()`)
3. Vérifier la présence de valeurs manquantes (NA)
4. Identifier une potentielle clé unique (identifiant)

## Fonction de base

In [24]:
def inspector(df):
    
    """
    Génère un rapport d'inspection complet pour un DataFrame.
    
    Paramètres:
    -----------
    df : pandas.DataFrame
        Le DataFrame à inspecter
    
    Retourne:
    ---------
    None (affiche le rapport dans le terminal)
    """
    
    # Debut de l'inspection
    print("#####     DEBUT DE L'INSPECTION     #####")
    
    # Structure du DataFrame avec df.shape
    print("\n----------------------")
    print("Structure du DataFrame:")
    print(f'Nb de lignes: {df.shape[0]} ; Nb de colonnes: {df.shape[1]}')
    
    # Types de données avec df.dtypes
    print("\n----------------------")
    print("Types de données:")
    print(df.dtypes)
    
    # Présence d'une potentielle clé unique (identifiant) avec df.nunique()
    print("\n----------------------")
    print("Nombre de valeurs uniques (pour identifiant PK / FK):")
    print(df.nunique())
    
    # Présence de valeurs manquantes avec df.isnull().sum()
    print("\n----------------------")
    print("Valeurs manquantes:")
    print(df.isnull().sum())
    
    # Fin de l'inspection
    print("\n#####     FIN DE L'INSPECTION     #####")

In [25]:
# Test de la fronction d'inspection sur le DataFrame customers
inspector(products)

#####     DEBUT DE L'INSPECTION     #####

----------------------
Structure du DataFrame:
Nb de lignes: 3286 ; Nb de colonnes: 3

----------------------
Types de données:
id_prod     object
price      float64
categ        int64
dtype: object

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
id_prod    3286
price      1454
categ         3
dtype: int64

----------------------
Valeurs manquantes:
id_prod    0
price      0
categ      0
dtype: int64

#####     FIN DE L'INSPECTION     #####

In [ ]:
#?inspector
#help(inspector)

#inspector()

Help on function inspector in module __main__:

inspector(df)
    Génère un rapport d'inspection complet pour un DataFrame.

    Paramètres:
    -----------
    df : pandas.DataFrame
        Le DataFrame à inspecter

    Retourne:
    ---------
    None (affiche le rapport dans le terminal)

Test de la fonction depuis le script `src/data_manager.py`

In [26]:
import sys
sys.path.append('../src')

from data_manager import inspector
#from src.data_manager import inspector

inspector(customers)

#####     DEBUT DE L'INSPECTION     #####

----------------------
Structure du DataFrame:
Nb de lignes: 8621 ; Nb de colonnes: 3

----------------------
Types de données:
client_id    object
sex          object
birth         int64
dtype: object

----------------------
Nombre de valeurs uniques (pour identifiant PK / FK):
client_id    8621
sex             2
birth          76
dtype: int64

----------------------
Valeurs manquantes:
client_id    0
sex          0
birth        0
dtype: int64

#####     FIN DE L'INSPECTION     #####

## Fonction avancée

In [27]:
def inspecter_dataframe(df, nom="DataFrame"):
    """
    Génère un rapport d'inspection complet pour un DataFrame.
    
    Paramètres:
    -----------
    df : pandas.DataFrame
        Le DataFrame à inspecter
    nom : str
        Le nom du DataFrame (pour l'affichage)
    
    Retourne:
    ---------
    None (affiche le rapport dans le terminal)
    """
    
    # Séparateur visuel
    separateur = "=" * 70
    
    # === EN-TÊTE ===
    print(f"\n{separateur}")
    print(f"📊 RAPPORT D'INSPECTION : {nom.upper()}")
    print(f"{separateur}\n")
    
    # === 1. DIMENSIONS ===
    print(f"📐 DIMENSIONS")
    print(f"   - Nombre de lignes   : {df.shape[0]:,}")
    print(f"   - Nombre de colonnes : {df.shape[1]}")
    print()
    
    # === 2. TYPES DE DONNÉES ===
    print(f"📋 COLONNES ET TYPES")
    print("-" * 40)
    for col in df.columns:
        print(f"   {col:25} → {df[col].dtype}")
    print()
    
    # === 3. VALEURS MANQUANTES ===
    print(f"❓ VALEURS MANQUANTES (NA)")
    print("-" * 40)
    na_counts = df.isna().sum()
    na_total = na_counts.sum()
    
    if na_total == 0:
        print("   ✅ Aucune valeur manquante !")
    else:
        print(f"   ⚠️  Total de valeurs manquantes : {na_total:,}")
        for col in df.columns:
            if na_counts[col] > 0:
                pct = (na_counts[col] / len(df)) * 100
                print(f"   - {col:25} : {na_counts[col]:,} ({pct:.1f}%)")
    print()
    
    # === 4. RECHERCHE DE CLÉ UNIQUE ===
    print(f"🔑 RECHERCHE DE CLÉ UNIQUE (IDENTIFIANT)")
    print("-" * 40)
    cle_trouvee = False
    
    for col in df.columns:
        nb_valeurs_uniques = df[col].nunique()
        nb_lignes = len(df)
        
        # Une colonne est une clé unique si chaque valeur est différente
        if nb_valeurs_uniques == nb_lignes:
            print(f"   ✅ '{col}' est une clé unique ({nb_valeurs_uniques:,} valeurs uniques)")
            cle_trouvee = True
        elif nb_valeurs_uniques == nb_lignes - df[col].isna().sum():
            # Cas où il y a des NA mais les valeurs non-NA sont uniques
            print(f"   ⚠️  '{col}' pourrait être une clé (unique hors NA)")
            cle_trouvee = True
    
    if not cle_trouvee:
        print("   ❌ Aucune colonne n'est une clé unique")
        print("   💡 Les colonnes avec le plus de valeurs uniques :")
        # Afficher les 3 colonnes avec le plus de valeurs uniques
        for col in df.columns[:3]:
            print(f"      - {col}: {df[col].nunique():,} valeurs uniques")
    print()
    
    # === 5. STATISTIQUES DESCRIPTIVES ===
    print(f"📈 STATISTIQUES DESCRIPTIVES")
    print("-" * 40)
    
    # Colonnes numériques
    cols_numeriques = df.select_dtypes(include=[np.number]).columns.tolist()
    if cols_numeriques:
        print("\n   Colonnes numériques :")
        display(df[cols_numeriques].describe().round(2))
    
    # Colonnes catégorielles (texte)
    cols_categorielles = df.select_dtypes(include=['object']).columns.tolist()
    if cols_categorielles:
        print("\n   Colonnes catégorielles :")
        display(df[cols_categorielles].describe())
    
    print(f"\n{separateur}")
    print(f"Fin du rapport pour {nom}")
    print(f"{separateur}\n")

### 💡 Comprendre la fonction

Notre fonction `inspecter_dataframe()` utilise plusieurs méthodes Pandas :

| Méthode | Ce qu'elle fait |
|---------|----------------|
| `df.shape` | Retourne (nb_lignes, nb_colonnes) |
| `df.dtypes` | Types de chaque colonne |
| `df.isna().sum()` | Compte les valeurs manquantes par colonne |
| `df.nunique()` | Nombre de valeurs uniques par colonne |
| `df.describe()` | Statistiques descriptives |

---

## 4. Inspection des 3 fichiers

Utilisons notre fonction pour inspecter chaque DataFrame.

In [10]:
?inspecter_dataframe
#help(inspecter_dataframe)

#inspecter_dataframe()

Signature: inspecter_dataframe(df, nom='DataFrame')
Docstring:
Génère un rapport d'inspection complet pour un DataFrame.

Paramètres:
-----------
df : pandas.DataFrame
    Le DataFrame à inspecter
nom : str
    Le nom du DataFrame (pour l'affichage)

Retourne:
---------
None (affiche le rapport dans le terminal)
File:      c:\users\rémijulien\appdata\local\temp\ipykernel_33120\2277465355.py
Type:      function

### 4.1 Inspection de `customers`

In [28]:
inspecter_dataframe(customers, "Customers")

======================================================================
📊 RAPPORT D'INSPECTION : CUSTOMERS
======================================================================

📐 DIMENSIONS
   - Nombre de lignes   : 8,621
   - Nombre de colonnes : 3

📋 COLONNES ET TYPES
----------------------------------------
   client_id                 → object
   sex                       → object
   birth                     → int64

❓ VALEURS MANQUANTES (NA)
----------------------------------------
   ✅ Aucune valeur manquante !

🔑 RECHERCHE DE CLÉ UNIQUE (IDENTIFIANT)
----------------------------------------
   ✅ 'client_id' est une clé unique (8,621 valeurs uniques)

📈 STATISTIQUES DESCRIPTIVES
----------------------------------------

   Colonnes numériques :

         birth
count  8621.00
mean   1978.28
std      16.92
min    1929.00
25%    1966.00
50%    1979.00
75%    1992.00
max    2004.00

   Colonnes catégorielles :

       client_id   sex
count       8621  8621
unique      8621     2
top       c_4410     f
freq           1  4490

======================================================================
Fin du rapport pour Customers
======================================================================

### 4.2 Inspection de `products`

In [29]:
inspecter_dataframe(products, "Products")

======================================================================
📊 RAPPORT D'INSPECTION : PRODUCTS
======================================================================

📐 DIMENSIONS
   - Nombre de lignes   : 3,286
   - Nombre de colonnes : 3

📋 COLONNES ET TYPES
----------------------------------------
   id_prod                   → object
   price                     → float64
   categ                     → int64

❓ VALEURS MANQUANTES (NA)
----------------------------------------
   ✅ Aucune valeur manquante !

🔑 RECHERCHE DE CLÉ UNIQUE (IDENTIFIANT)
----------------------------------------
   ✅ 'id_prod' est une clé unique (3,286 valeurs uniques)

📈 STATISTIQUES DESCRIPTIVES
----------------------------------------

   Colonnes numériques :

         price    categ
count  3286.00  3286.00
mean     21.86     0.37
std      29.85     0.62
min       0.62     0.00
25%       6.99     0.00
50%      13.08     0.00
75%      22.99     1.00
max     300.00     2.00

   Colonnes catégorielles :

       id_prod
count     3286
unique    3286
top     0_1421
freq         1

======================================================================
Fin du rapport pour Products
======================================================================

### 4.3 Inspection de `transactions`

In [30]:
inspecter_dataframe(transactions, "Transactions")

======================================================================
📊 RAPPORT D'INSPECTION : TRANSACTIONS
======================================================================

📐 DIMENSIONS
   - Nombre de lignes   : 1,048,575
   - Nombre de colonnes : 4

📋 COLONNES ET TYPES
----------------------------------------
   id_prod                   → object
   date                      → object
   session_id                → object
   client_id                 → object

❓ VALEURS MANQUANTES (NA)
----------------------------------------
   ⚠️  Total de valeurs manquantes : 1,444,164
   - id_prod                   : 361,041 (34.4%)
   - date                      : 361,041 (34.4%)
   - session_id                : 361,041 (34.4%)
   - client_id                 : 361,041 (34.4%)

🔑 RECHERCHE DE CLÉ UNIQUE (IDENTIFIANT)
----------------------------------------
   ❌ Aucune colonne n'est une clé unique
   💡 Les colonnes avec le plus de valeurs uniques :
      - id_prod: 3,265 valeurs uniques
      - date: 687,419 valeurs uniques
      - session_id: 345,505 valeurs uniques

📈 STATISTIQUES DESCRIPTIVES
----------------------------------------

   Colonnes catégorielles :

       id_prod                        date session_id client_id
count   687534                      687534     687534    687534
unique    3265                      687419     345505      8600
top      1_369  2021-10-06 21:29:59.752585   s_118668    c_1609
freq      2340                           2         14     25586

======================================================================
Fin du rapport pour Transactions
======================================================================

### 📝 Synthèse de l'inspection

À compléter après l'inspection :

| Fichier | Lignes | Clé unique | NA ? | Observations |
|---------|--------|------------|------|-------------|
| customers | ... | ... | ... | ... |
| products | ... | ... | ... | ... |
| transactions | ... | ... | ... | ... |

**=> nécessité de supprimer les données manquantes de la df `transactions` avant de procéder à la jointure des tables.**

In [4]:
transactions = transactions.dropna()

---

## 5. Jointure des fichiers

### 🎯 Objectif
Créer un DataFrame unifié contenant toutes les informations : transactions + détails produits + détails clients.

### 🔗 Identifier les clés de jointure

Pour joindre des tables, il faut identifier les **colonnes communes** :

In [32]:
# Afficher les colonnes de chaque table
print("Colonnes CUSTOMERS    :", list(customers.columns))
print("Colonnes PRODUCTS     :", list(products.columns))
print("Colonnes TRANSACTIONS :", list(transactions.columns))

Colonnes CUSTOMERS    : ['client_id', 'sex', 'birth']
Colonnes PRODUCTS     : ['id_prod', 'price', 'categ']
Colonnes TRANSACTIONS : ['id_prod', 'date', 'session_id', 'client_id']

### 🔍 Analyse des relations

```
┌─────────────┐         ┌──────────────────┐         ┌─────────────┐
│  CUSTOMERS  │         │   TRANSACTIONS   │         │  PRODUCTS   │
├─────────────┤         ├──────────────────┤         ├─────────────┤
│ client_id   │◄───────►│ client_id        │         │ id_prod     │
│ sex         │         │ id_prod          │◄───────►│ price       │
│ birth       │         │ date             │         │ categ       │
│             │         │ session_id       │         │             │
└─────────────┘         └──────────────────┘         └─────────────┘
```

**Clés de jointure identifiées :**
- `transactions.client_id` ↔ `customers.client_id`
- `transactions.id_prod` ↔ `products.id_prod`

### 📚 Rappel : Les types de jointures

| Type | Description | Utilisation |
|------|-------------|-------------|
| `inner` | Garde uniquement les lignes présentes dans les 2 tables | Par défaut, le plus strict |
| `left` | Garde toutes les lignes de la table de gauche | Conserver toutes les transactions |
| `right` | Garde toutes les lignes de la table de droite | Rarement utilisé |
| `outer` | Garde toutes les lignes des 2 tables | Union complète |

### 5.1 Étape 1 : Joindre transactions et products

In [33]:
# Vérifier les noms de colonnes pour la jointure
print("Dans transactions, la colonne produit s'appelle :", 
      [col for col in transactions.columns if 'prod' in col.lower()])
print("Dans products, la colonne produit s'appelle :", 
      [col for col in products.columns if 'prod' in col.lower() or 'id' in col.lower()])

Dans transactions, la colonne produit s'appelle : ['id_prod']
Dans products, la colonne produit s'appelle : ['id_prod']

In [5]:
# Jointure transactions + products
# On utilise 'left' pour garder toutes les transactions
# même si un produit n'est pas trouvé dans la table products

df_transaction_produit = transactions.merge(
    products,
    left_on='id_prod',      # Colonne dans transactions
    right_on='id_prod',     # Colonne dans products
    how='left'              # Type de jointure
)

print(f"✅ Jointure transactions + products effectuée")
print(f"   - Lignes avant : {len(transactions):,}")
print(f"   - Lignes après : {len(df_transaction_produit):,}")
print(f"   - Colonnes     : {list(df_transaction_produit.columns)}")

✅ Jointure transactions + products effectuée
   - Lignes avant : 687,534
   - Lignes après : 687,534
   - Colonnes     : ['id_prod', 'date', 'session_id', 'client_id', 'price', 'categ']

In [41]:
# Vérifier s'il y a des produits non trouvés (NA dans price ou categ)
produits_manquants = df_transaction_produit['price'].isna().sum()
print(f"\n⚠️  Produits non trouvés dans la table products : {produits_manquants}")

if produits_manquants > 0:
    print("\nDétail des produits manquants :")
    display(df_transaction_produit[df_transaction_produit['price'].isna()]['id_prod'].value_counts().head(10))

⚠️  Produits non trouvés dans la table products : 0

### 5.2 Étape 2 : Joindre avec customers

In [6]:
# Jointure avec customers
transactions_enrichies = df_transaction_produit.merge(
    customers,
    on='client_id',         # Colonne commune (même nom dans les 2 tables)
    how='left'
)

print(f"✅ Jointure avec customers effectuée")
print(f"   - Lignes : {len(transactions_enrichies):,}")
print(f"   - Colonnes : {list(transactions_enrichies.columns)}")

✅ Jointure avec customers effectuée
   - Lignes : 687,534
   - Colonnes : ['id_prod', 'date', 'session_id', 'client_id', 'price', 'categ', 'sex', 'birth']

In [10]:
# Vérifier s'il y a des clients non trouvés
clients_manquants = transactions_enrichies['sex'].isna().sum()
print(f"\n⚠️  Clients non trouvés dans la table customers : {clients_manquants}")

⚠️  Clients non trouvés dans la table customers : 0

### 5.3 Vérification du résultat final

In [44]:
# Aperçu du DataFrame final
print("📊 DATAFRAME UNIFIÉ")
print("=" * 50)
print(f"Dimensions : {transactions_enrichies.shape[0]:,} lignes × {transactions_enrichies.shape[1]} colonnes\n")
display(transactions_enrichies.head())

📊 DATAFRAME UNIFIÉ
==================================================
Dimensions : 687,534 lignes × 8 colonnes

,id_prod,date,session_id,client_id,price,categ,sex,birth
0,0_1259,2021-03-01 00:01:07.843138,s_1,c_329,11.99,0,f,1967
1,0_1390,2021-03-01 00:02:26.047414,s_2,c_664,19.37,0,m,1960
2,0_1352,2021-03-01 00:02:38.311413,s_3,c_580,4.50,0,m,1988
3,0_1458,2021-03-01 00:04:54.559692,s_4,c_7912,6.55,0,f,1989
4,0_1358,2021-03-01 00:05:18.801198,s_5,c_2033,16.49,0,f,1956

In [45]:
# Inspection du DataFrame unifié
inspecter_dataframe(transactions_enrichies, "DataFrame unifié")

======================================================================
📊 RAPPORT D'INSPECTION : DATAFRAME UNIFIÉ
======================================================================

📐 DIMENSIONS
   - Nombre de lignes   : 687,534
   - Nombre de colonnes : 8

📋 COLONNES ET TYPES
----------------------------------------
   id_prod                   → object
   date                      → object
   session_id                → object
   client_id                 → object
   price                     → float64
   categ                     → int64
   sex                       → object
   birth                     → int64

❓ VALEURS MANQUANTES (NA)
----------------------------------------
   ✅ Aucune valeur manquante !

🔑 RECHERCHE DE CLÉ UNIQUE (IDENTIFIANT)
----------------------------------------
   ❌ Aucune colonne n'est une clé unique
   💡 Les colonnes avec le plus de valeurs uniques :
      - id_prod: 3,265 valeurs uniques
      - date: 687,419 valeurs uniques
      - session_id: 345,505 valeurs uniques

📈 STATISTIQUES DESCRIPTIVES
----------------------------------------

   Colonnes numériques :

           price      categ      birth
count  687534.00  687534.00  687534.00
mean       17.49       0.45    1977.82
std        18.24       0.59      13.61
min         0.62       0.00    1929.00
25%         8.99       0.00    1970.00
50%        13.99       0.00    1980.00
75%        19.08       1.00    1987.00
max       300.00       2.00    2004.00

   Colonnes catégorielles :

       id_prod                        date session_id client_id     sex
count   687534                      687534     687534    687534  687534
unique    3265                      687419     345505      8600       2
top      1_369  2021-10-06 21:29:59.752585   s_118668    c_1609       m
freq      2340                           2         14     25586  344841

======================================================================
Fin du rapport pour DataFrame unifié
======================================================================

## 6. Enrichissement des données

### 6.1 Segmentation clientèle B2B et B2C
Une analyse ultérieure des données de vente par client montre que 2 clients se démarquent fortement en terme de volumétrie et de CA réalisé. Il est fort probable que ces 2 clients appartiennent à une catégorie B2B, contraitement au reste des clients de catégorie B2C.  
Cette information peut être apportée au dataset afin de l'enrichir.

In [17]:
# Calcul du CA généré par client
ca_par_client = transactions_enrichies.groupby('client_id')['price'].sum().reset_index()
#ca_par_client

# Tri par ordre décroissant de CA   
ca_par_client = ca_par_client.sort_values(by='price', ascending=False).reset_index(drop=True)
ca_par_client.head(10)

  client_id      price
0    c_1609  326039.89
1    c_4958  290227.03
2    c_6714  153918.60
3    c_3454  114110.57
4    c_1570    5285.82
5    c_3263    5276.87
6    c_2140    5260.18
7    c_2899    5214.05
8    c_7319    5155.77
9    c_7959    5135.75

In [7]:
client_b2b = ['c_1609' , 'c_4958', 'c_6714', 'c_3454']
transactions_enrichies["segment_client"] = transactions_enrichies['client_id'].apply(lambda x: 'B2B' if x in client_b2b else 'B2C')

transactions_enrichies.head()

,id_prod,date,session_id,client_id,price,categ,sex,birth,segment_client
0,0_1259,2021-03-01 00:01:07.843138,s_1,c_329,11.99,0,f,1967,B2C
1,0_1390,2021-03-01 00:02:26.047414,s_2,c_664,19.37,0,m,1960,B2C
2,0_1352,2021-03-01 00:02:38.311413,s_3,c_580,4.50,0,m,1988,B2C
3,0_1458,2021-03-01 00:04:54.559692,s_4,c_7912,6.55,0,f,1989,B2C
4,0_1358,2021-03-01 00:05:18.801198,s_5,c_2033,16.49,0,f,1956,B2C

### 6.2 Age des clients
Dans la suite des analyses, un focus sur l'âge des clients sera demandé.  
Calculons dès maintenant cette donnée et intégrons la au dataset analytique.

In [ ]:
# Définition de l'année courante
# Alternative : calculer l'age du client à la date d'achat (extractionn de l'année à partir de la date d'achat)
current_year = current_date = date.today().year
print(current_year)

# Calcul de l'âge du client par rapport à l'année courante
transactions_enrichies['age_client'] =  current_year - transactions_enrichies['birth']
transactions_enrichies.head()

2026

,id_prod,date,session_id,client_id,price,categ,sex,birth,segment_client,age_client
0,0_1259,2021-03-01 00:01:07.843138,s_1,c_329,11.99,0,f,1967,B2C,59
1,0_1390,2021-03-01 00:02:26.047414,s_2,c_664,19.37,0,m,1960,B2C,66
2,0_1352,2021-03-01 00:02:38.311413,s_3,c_580,4.50,0,m,1988,B2C,38
3,0_1458,2021-03-01 00:04:54.559692,s_4,c_7912,6.55,0,f,1989,B2C,37
4,0_1358,2021-03-01 00:05:18.801198,s_5,c_2033,16.49,0,f,1956,B2C,70

## 7 Sauvegarde du dataset finalisé

A ce stade il semble judicieux de conserver le résultat des préparations réalisées dans ce notebook.  
Ce nouveau dataset permettra de réaliser les analyses demandées par Julie et Anabelle.

In [10]:
# Sauvegarder le DataFrame unifié pour les prochaines analyses
transactions_enrichies.to_csv(DATA_PATH + "processed/transactions_enrichies.csv", index=False)

print("✅ Données sauvegardées dans 'data/processed/transactions_enrichies.csv'")

✅ Données sauvegardées dans 'data/processed/transactions_enrichies.csv'

---

## 📝 Récapitulatif

### Ce que nous avons appris :

| Compétence | Méthodes utilisées |
|------------|-------------------|
| Charger des données | `pd.read_csv()` |
| Inspecter un DataFrame | `.shape`, `.dtypes`, `.isna()`, `.nunique()`, `.describe()` |
| Joindre des tables | `.merge()` avec `left_on`, `right_on`, `how` |

### Prochaines étapes :
- Compléter les analyses pour Annabelle (courbe de Lorenz, Top/Flop)
- Réaliser les 5 corrélations pour Julie
- Préparer la présentation CODIR